// https://projects.neoforged.net/
plugins {
    id 'java-library'
    id 'net.neoforged.moddev.legacyforge' version '2.0.137'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

mixin {
    add sourceSets.main, 'patched.refmap.json'
    config 'mixins.patched.json'
}

tasks.named('jar', Jar).configure {
    manifest.attributes([
        'MixinConfigs': 'mixins.patched.json'
    ])
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly(annotationProcessor('io.github.llamalad7:mixinextras-common:0.4.1'))
    jarJar(implementation('io.github.llamalad7:mixinextras-forge')) {
        version {
            strictly '[0.4.1,)'
            prefer '0.4.1'
        }
    }
}

legacyForge {
    version = "${minecraft_version}-${loader_version}"

    mods {
        patched {
            sourceSet sourceSets.main
            sourceSet project(':PatchedMod.Common').sourceSets.main
        }
    }

    parchment {
        minecraftVersion = "${minecraft_version}"
        mappingsVersion = "${mappings_version}"
    }

    runs {
        configureEach {
            additionalRuntimeClasspathConfiguration.extendsFrom configurations.shadow
        }

        client {
            client()
            ideName = 'runPatchedModClientForge1_19_2'
            if (rootProject.findProperty('minecraft_username') != null) {
                programArguments.addAll('--uuid', rootProject.findProperty('minecraft_uuid'), '--username', rootProject.findProperty('minecraft_username'))
            }
        }
        server {
            server()
            ideName = 'runPatchedModServerForge1_19_2'
        }
        data {
            data()
            ideName = 'runPatchedModClientDataForge1_19_2'
        }
    }
}