// https://projects.neoforged.net/
plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.137'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

configurations {
    shadow {}
    minecraftLibrary {}
    implementation.extendsFrom minecraftLibrary
}

dependencies {
    shadow (minecraftLibrary("com.github.EnderTurret:Patched:$patched_version")) {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
}

neoForge {
    version = "${loader_version}"

    mods {
        patched {
            sourceSet sourceSets.main
            sourceSet project(':PatchedMod.Common').sourceSets.main
        }
    }

    parchment {
        minecraftVersion = "${minecraft_version}"
        mappingsVersion = "${mappings_version}"
    }

    runs {
        configureEach {
            additionalRuntimeClasspathConfiguration.extendsFrom configurations.minecraftLibrary
        }

        client {
            client()
            ideName = 'runPatchedModClientNeoForge1_21_11'
            if (rootProject.findProperty('minecraft_username') != null) {
                programArguments.addAll('--uuid', rootProject.findProperty('minecraft_uuid'), '--username', rootProject.findProperty('minecraft_username'))
            }
        }
        server {
            server()
            ideName = 'runPatchedModServerNeoForge1_21_11'
        }
        clientData {
            clientData()
            ideName = 'runPatchedModClientDataNeoForge1_21_11'
        }
    }
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar).configure {
    archiveClassifier = ''

    configurations = [project.configurations.shadow]

    from (rootDir) {
        include 'LICENSE.txt'
    }
}

jar.enabled = false

artifacts {
    archives shadowJar
    shadow shadowJar
}