// https://projects.neoforged.net/
plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.137'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "${loader_version}"

    mods {
        patched {
            sourceSet sourceSets.main
            sourceSet project(':PatchedMod.Common').sourceSets.main
        }
    }

    parchment {
        minecraftVersion = "${minecraft_version}"
        mappingsVersion = "${mappings_version}"
    }

    runs {
        configureEach {
            additionalRuntimeClasspathConfiguration.extendsFrom configurations.shadow
        }

        client {
            client()
            ideName = 'runPatchedModClientNeoForge1_21_11'
            if (rootProject.findProperty('minecraft_username') != null) {
                programArguments.addAll('--uuid', rootProject.findProperty('minecraft_uuid'), '--username', rootProject.findProperty('minecraft_username'))
            }
        }
        server {
            server()
            ideName = 'runPatchedModServerNeoForge1_21_11'
        }
        clientData {
            clientData()
            ideName = 'runPatchedModClientDataNeoForge1_21_11'
        }
    }
}

tasks.named('jar', Jar).configure {
    // Add the Patched library to the built jar.
    dependsOn configurations.shadow
    from {
        configurations.shadow.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }

    from (rootDir) {
        include 'LICENSE-small.txt'
    }

    exclude 'net/enderturret/patchedmod/forge/data/**'
}