// https://projects.neoforged.net/
plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.137'
}

configurations {
    shadow {}
    minecraftLibrary {}
    implementation.extendsFrom minecraftLibrary
}

dependencies {
    implementation (project(':PatchedMod.Common'))

    shadow (minecraftLibrary("com.github.EnderTurret:Patched:$patchedVersion")) {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    sourceShadow ("com.github.EnderTurret:Patched:$patchedVersion:sources") {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
}

neoForge {
    version = '21.11.25-beta'

    mods {
        patched {
            sourceSet sourceSets.main
            sourceSet project(':PatchedMod.Common').sourceSets.main
        }
    }

    parchment {
        // https://parchmentmc.org/docs/getting-started
        // https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
        minecraftVersion = '1.21.11'
        mappingsVersion = '2025.12.20'
    }

    runs {
        configureEach {
            additionalRuntimeClasspathConfiguration.extendsFrom configurations.minecraftLibrary
        }

        client {
            client()
            ideName = 'runPatchedModNeoForgeClient'
            gameDirectory = project.file('run/1.21')
        }
        server {
            server()
            ideName = 'runPatchedModNeoForgeServer'
        }
        clientData {
            clientData()
            ideName = 'runPatchedModNeoForgeClientData'
        }
    }
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar).configure {
    archiveClassifier = ''

    configurations = [project.configurations.shadow]

    from (rootDir) {
        include 'LICENSE.txt'
    }
}

jar.enabled = false

artifacts {
    archives shadowJar
    shadow shadowJar
}