pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'PatchedMod'

include('common', 'neoforge-1.21.11', 'fabric-1.21.11')
project(':common').name = 'PatchedMod.Common'
project(':neoforge-1.21.11').name = 'PatchedMod.NeoForge.1.21.11'
project(':fabric-1.21.11').name = 'PatchedMod.Fabric.1.21.11'