modLoader="javafml"
loaderVersion="[40,)"
license="LGPL v2.1"
issueTrackerURL="https://github.com/EnderTurret/PatchedMod/issues"

[[mods]]
    modId="patched"
    displayName="Patched"
    description='''
    Adds the ability to patch json files.
    '''
    version="${file.jarVersion}"
    authors="EnderTurret"
    displayURL="https://github.com/EnderTurret/PatchedMod"

[[dependencies.patched]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.patched]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"