modLoader="javafml"
loaderVersion="[40,)"
license="LGPL v2.1"

[[mods]]
    modId="patched"
    displayName="Patched"
    description='''
    Adds the ability to patch json files.
    '''
    version="${file.jarVersion}"
    authors="EnderTurret"

[[dependencies.foxxeworigins]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.foxxeworigins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"