plugins {
    // https://maven.fabricmc.net/net/fabricmc/fabric-loom/
    id 'net.fabricmc.fabric-loom-remap' version '1.15.3'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

loom {
    accessWidenerPath = file("${rootDir}/fabric-${minecraft_version}/src/main/resources/patched.accesswidener")

    // Due to an incredible oversight(?) in Loom, these actually do nothing.
    // You cannot change the configuration name from the default, which is derived from the project name.
    runs {
        client {
            configName = 'runPatchedClientFabric1_21_11'
        }

        server {
            configName = 'runPatchedServerFabric1_21_11'
        }
    }

    runConfigs.configureEach {
        ideConfigGenerated = true
    }
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar).configure {
    configurations = [project.configurations.shadow]
}

tasks.register('remappedShadowJar', net.fabricmc.loom.task.RemapJarTask) {
    archiveClassifier = ''
    input = tasks.shadowJar.archiveFile
    dependsOn shadowJar
    from (rootDir) {
        include 'LICENSE.txt'
    }
}

artifacts {
    archives remappedShadowJar
    shadow shadowJar
}

tasks.named('processResources', ProcessResources).configure {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}