java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
    maven {
        url = 'https://libraries.minecraft.net'
    }
}

dependencies {
    compileOnly 'com.google.code.gson:gson:2.8.9'
    compileOnly 'org.jetbrains:annotations:26.0.1'
    compileOnly 'org.slf4j:slf4j-api:1.8.0-beta4'
    compileOnly 'com.mojang:brigadier:1.0.18'
    compileOnly 'com.mojang:datafixerupper:4.1.27'
}